### ISSUE TITLE
Doesn't work with dynamic require?

### ISSUE THREAD

**Issue by AprilArcus** [WearyMonkey/ngtemplate-loader#10]
I have a folder full of SVGs that I want to load with `ngtemplate-loader`. When I require them individually, everything works great, but when I try to require the entire folder by putting `require.context('.', false, /\.svg$/);` in an `index.js` file, `ngtemplate-loader` fails silently without adding them to `$templateCache`. The dynamic require works fine with e.g. `file-loader`, but I'm having trouble debugging this combination.

**Comment by AprilArcus** [comment]
Here is the module produced by manually requiring each SVG:

```JavaScript
/* 157 */
/***/ function(module, exports, __webpack_require__) {

    __webpack_require__(235);
    ...
    __webpack_require__(287);

/***/ },
```

and here is the module produced by the dynamic require:

```JavaScript
/* 189 */
/***/ function(module, exports, __webpack_require__) {

    var map = {
        "./icon-add.svg": 236,
        ...
        "./icon-warning.svg": 288
    };
    function webpackContext(req) {
        return __webpack_require__(webpackContextResolve(req));
    };
    function webpackContextResolve(req) {
        return map[req] || (function() { throw new Error("Cannot find module '" + req + "'.") }());
    };
    webpackContext.keys = function webpackContextKeys() {
        return Object.keys(map);
    };
    webpackContext.resolve = webpackContextResolve;
    module.exports = webpackContext;
    webpackContext.id = 189;


/***/ },
```

It appears that the latter construction will not call the IIFEs wrapping each template at load time, which breaks `ngtemplate-loader` / angular's side-effects driven module system.

**Comment by AprilArcus** [comment]
I worked around this issue by manually calling the resolve function with each key at the import site.

```JavaScript
var ngtemplates = require.context('.', false, /\.svg$/);
ngtemplates.keys().forEach(function(key) {
	ngtemplates(key);
});
```

I will write this up and add it to `README.md` in a PR.

**Comment by WearyMonkey** [comment]
Thanks for that.
