### ISSUE TITLE
Load templates from different paths

### ISSUE THREAD

**Issue by aganglada** [WearyMonkey/ngtemplate-loader#16]
Hello, 

I have a project which one I have different paths from I want to load my templates.

My question is, is there any way to specify different "&relativeTo=" in the config?

A solution for this could be super useful.

Thanks in advance!

**Comment by WearyMonkey** [comment]
Hi @aganglada,

You could do this by writing different loader tests in your webpack.config.js, something like:

```javascript
module.loaders: [
  {
    include: [
      path.resolve(__dirname, "app/src")
    ],
    loader: "ngtemplate?relativeTo=foo!html"
  },
  {
    include: [
      path.resolve(__dirname, "app/test")
    ],
    loader: "ngtemplate?relativeTo=baa!html"
  }
]
```

You can read more about the loader tests [here](http://webpack.github.io/docs/configuration.html#module-loaders)

**Comment by aganglada** [comment]
Thanks @WearyMonkey I will try it out :)
