### ISSUE TITLE
Cannot resolve module 'html'

### ISSUE THREAD

**Issue by rob-balfre** [WearyMonkey/ngtemplate-loader#27]
I'm trying to get the ngtemplate-loader and baggage working together but keep getting this error:

`Module not found: Error: Cannot resolve module 'html' in /app-name/src/directives/directive_name`

My folder structure is the same as your README example. Bit stumped!

**Comment by WearyMonkey** [comment]
Have you tried `npm install html-loader --save-dev` ?

**Comment by rob-balfre** [comment]
Seemed to do the trick I think :+1:

**Comment by alex88** [comment]
Just encountered the same issue, maybe worth adding it as peerDependency?

**Comment by WearyMonkey** [comment]
@alex88 no I don't think so, as `html-loader` is only one option and part of the configuration. You could also use it with `raw-loader` or any number of template loaders.

**Comment by alex88** [comment]
@WearyMonkey oh nvm then, your right!

**Comment by edencore** [comment]
At least this should be mentioned in README I think. I thought it was something with my paths before I found this issue
