### ISSUE TITLE
interpolateName + placeholders

### ISSUE THREAD

**Issue by mdreizin** [WearyMonkey/ngtemplate-loader#29]
It would be nice if all query params could be processed via `loaderUtils.interpolateName()` like it does [file-loader](https://github.com/webpack/file-loader/blob/master/index.js#L11-L15). Also it would be nice if developers can use some placeholders for instance like [baggage-loader](https://github.com/deepsweet/baggage-loader/blob/master/lib/util.js#L13-L16).

It would be very useful when you have more then one module and you don't need to create `ngtemplate-loader` for each of them.

**Comment by WearyMonkey** [comment]
Those would be nice, I'll look into it :)

**Comment by mdreizin** [comment]
@WearyMonkey Looking forward to get it.

placeholders

```js
{
    test: /(.*)\.html$/,
    loader: 'ngtemplate',
    query: {
        module: 'test.[dir]',
        relativeTo: path.join(__dirname, path.sep)
    }
}
```

interpolateName

```js
{
    test: /(.*)\.html$/,
    loader: 'ngtemplate',
    query: {
        module: 'test.[1]',
        regExp: __dirname,
        context: __dirname,
        relativeTo: path.join(__dirname, path.sep)
    }
}
```

**Comment by denich** [comment]
+1

**Comment by amcdnl** [comment]
@mdreizin did anything ever progress w/ this? Very interested.

**Comment by mdreizin** [comment]
@amcdnl I don't have any plans to implement this feature :(

Probably @WearyMonkey will do that.

**Comment by amcdnl** [comment]
Did you have a work around you came up with?

**Comment by mdreizin** [comment]
@amcdnl No, I don't have workaround for that, but from my point of view it is easy to implement.

@WearyMonkey may extract that approach from https://github.com/mdreizin/angular-translate-loader/blob/master/src/interpolateValue.js

**Comment by WearyMonkey** [comment]
@amcdnl I'll take a look at this week.

**Comment by amcdnl** [comment]
@WearyMonkey I ended up forking, I needed a different export too so didn't make sense to bother u with this. https://github.com/swimlane/ngtemplate-loader/blob/master/index.js

**Comment by WearyMonkey** [comment]
Fixed in https://github.com/WearyMonkey/ngtemplate-loader/commit/cd04b0b16d5e30e030e51b5f9f212552d086c975
