### ISSUE TITLE
Invalid HTML causes Webpack to Hang

### ISSUE THREAD

**Issue by voor** [WearyMonkey/ngtemplate-loader#31]
Sorry I don't really have any sort of log output, since Webpack will just idle for ages whenever UglifyJS2 gets a hold of invalid HTML.  Some of the causes we've had that triggered this:

- Not properly closing tags `<div><div></div>` or some such
- Invalid HTML syntax like `class""` instead of `class=""`

This wouldn't be such an issue, except the log doesn't indicate any issues at all.  Is there a way to see the JavaScript strings in a verbose mode output to the logs just as a sanity check?

**Comment by WearyMonkey** [comment]
Hi @voor, I doubt this is an issue with `ngtemplate-loader` as it doesn't do any HTML parsing/processing.  It might be an issue the `html-loader` or the template loader you are using.

Could you please post your `webpack.config` so I can provide more suggestions?

**Comment by e-cloud** [comment]
@voor , you can use some `htmllint` loader in `preloader` for such kind of check.
