### ISSUE TITLE
Doesn't works on windows

### ISSUE THREAD

**Issue by huston007** [WearyMonkey/ngtemplate-loader#4]
As we know, the windows path separator is dramatic different from other systems. So shouldn't we handle it in this loader?

**Comment by epelc** [comment]
Will there be a fix for this soon?

**Comment by WearyMonkey** [comment]
Hi @epelc, I will take a look tonight.

**Comment by epelc** [comment]
@WearyMonkey Thanks this looks like it will fix my directives loading issue

**Comment by icfantv** [comment]
I'm confused here.  I have everything set up with *nix style path separators and it works great.  When I try to build on windows it barfs.  I see [this](https://github.com/WearyMonkey/ngtemplate-loader#path-separators-or-using-on-windows), but the way I'm reading the above comments, the build tool (aka, this library) should be properly handling my *nix style paths but I don't think it is.

Can someone please explain what this fix is supposed to do?  Is it supposed to make the build platform agnostic?

**Comment by victordidenko** [comment]
@WearyMonkey in version 2.0.0, while build on Windows, template path separators become "\\\\". In version 1.3.1 everything was working fine.

**Comment by victordidenko** [comment]
Fixed in version 2.0.1, thank you!
