### ISSUE TITLE
New NPM release

### ISSUE THREAD

**Issue by jagregory** [WearyMonkey/ngtemplate-loader#48]
Hey everyone, I'd like to use the `requireAngular` feature but a release hasn't been pushed to NPM yet which contains it.

**Comment by christianacca** [comment]
In the meantime you can install this package directly from the commit in github:

```cmd
npm install github:WearyMonkey/ngtemplate-loader#63e3461d8b1298de913e3528766068260915ae1f --save-dev
```

**Comment by pselden** [comment]
👍

**Comment by DSpeichert** [comment]
Important: version 1.3.1 in this repo is not the same as 1.3.1 i npm.

**Comment by WearyMonkey** [comment]
2.0.0 released.
