### ISSUE TITLE
Unique Template Modules Per Entry Point?

### ISSUE THREAD

**Issue by bmbell** [WearyMonkey/ngtemplate-loader#51]
Say I have 3 entry points:

config.entry = {
        "a": [root("modules/a")],
        "b": [root("modules/b")],
        "c": [root("modules/c")]
};

I'd like to be able to create template modules for each of these:

// angular.module('aTemplates').run(['$templateCache', ...
// angular.module('bTemplates').run(['$templateCache', ...
// angular.module('cTemplates').run(['$templateCache', ...

Is this possible?

**Comment by WearyMonkey** [comment]
Can not be achieved using `module` parameter interpolation. https://github.com/WearyMonkey/ngtemplate-loader/commit/cd04b0b16d5e30e030e51b5f9f212552d086c975
