### ISSUE TITLE
Return templateUrl from require() call

### ISSUE THREAD

**Issue by srigi** [WearyMonkey/ngtemplate-loader#6]
Thank you for this loader. It does great job. However it leads to some code duplication. Calling `require('some.html')` will generate JS code that only adds `some.html` to `$templateCache`. It would be great if that `require()` call would return `templateUrl`. It can be very clear on directive example:

```js
require('./stateDebugger.html');

module.directive('stateDebugger', function($state) {
  return {
    templateUrl: 'shared/directives/stateDebugger.html',
    link: function() {  /* some code */ }
  };
});
```

As you can see I have to manually set `templateUrl` of the directive. It would be great if this would be possible:
```js
templateUrl: require('./stateDebugger.html'),
```

**Comment by WearyMonkey** [comment]
Nice idea! I'll look into it.

**Comment by srigi** [comment]
You are awesome, thank you.
