### ISSUE TITLE
DeprecationWarning: loaderUtils

### ISSUE THREAD

**Issue by amitport** [WearyMonkey/ngtemplate-loader#60]
https://github.com/WearyMonkey/ngtemplate-loader/blob/b5390e0f2e75e0c602e1494584c6cbff3b3f2252/index.js#L8
causes: (with webpack 2.5)
```
DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
```

**Comment by thekip** [comment]
same issue

**Comment by WearyMonkey** [comment]
Fixed in https://github.com/WearyMonkey/ngtemplate-loader/commit/0a488ef988806e3658c76b8949765b0a0c058954
