### ISSUE TITLE
Stopped working with html-loader v1.0.0

### ISSUE THREAD

**Issue by cb-eli** [WearyMonkey/ngtemplate-loader#85]
html-loader was updated to v1.0.0 with breaking changes. Since then ngtemplate-loader is breaking my build.

Everyone have the same issue?
Somebody have a fix for that?

**Comment by benochr** [comment]
Same problem here. 

It seems that the output of html-loader changed in v1.0.0.

In version 0.5.5 the output looked like this:
`module.exports = "... html ...";`

In version 1.1.0 the output has changed to:
```
// Module
var code = "... html ...";
// Exports
module.exports = code;
```

**Comment by benochr** [comment]
Because of this change following code is no longer working as intended.

```
if (content.match(/^module\.exports/)) {
        var firstQuote = findQuote(content, false);
        var secondQuote = findQuote(content, true);
        html = content.substr(firstQuote, secondQuote - firstQuote + 1);
} else {
        html = content;
}
```

**Comment by peterpoe** [comment]
Hey I have provided an alternative fix here #87 that adds compatibility with file-loader for stuff like <img src="..."> replacement

**Comment by cb-eli** [comment]
@WearyMonkey can you merge, please? :)

**Comment by WearyMonkey** [comment]
Sorry for the delay, I've released it now.
